/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_CHAT_H_RPCGEN
#define _RPC_CHAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define RPCCHATPROG 0x20000099
#define RPCCHATVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define WRITE 1
extern  int * write_1(char **, CLIENT *);
extern  int * write_1_svc(char **, struct svc_req *);
#define GETCHAT 2
extern  char ** getchat_1(void *, CLIENT *);
extern  char ** getchat_1_svc(void *, struct svc_req *);
extern int rpcchatprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define WRITE 1
extern  int * write_1();
extern  int * write_1_svc();
#define GETCHAT 2
extern  char ** getchat_1();
extern  char ** getchat_1_svc();
extern int rpcchatprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_CHAT_H_RPCGEN */
