/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_chat.h"
#include <stdio.h>
#include <stdlib.h>

#define FILE_NAME "chat.txt"

int *
write_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;
	printf("New write: %s\n", *argp);
	
	// Open file to append new message
	FILE * file = fopen(FILE_NAME, "a");
	if (file == NULL) {
		result = 0;
		return &result;
	}	
	
	// Write message to file
	fprintf(file, "%s", *argp);
	result = 1;
	
	fclose(file);
	return &result;
}

char **
getchat_1_svc(void *argp, struct svc_req *rqstp)
{
	FILE * file = fopen(FILE_NAME, "rb");
	
	if (file == NULL) {
		return NULL;
	}
	
	// Find file size
	fseek(file, 0, SEEK_END);
	size_t length = ftell(file);
	fseek(file, 0, SEEK_SET);
	
	static char * result = 0;
	result = (char*) malloc(length+1);
	if (result == NULL) {
		fclose(file);
		return NULL;
	}
	
	// Read and return the entire file as a string
	fread(result, length, 1, file);
	result[length] = '\0';
	
	fclose(file);
	return &result;
}
